/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Inventory;

import java.time.temporal.ChronoUnit;
import javax.swing.*;
import java.sql.*;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author olirv
 */
public class cancelorder extends javax.swing.JFrame {
    
    Connection con;
    Statement st;
    PreparedStatement ps;
    ResultSet rs;
    /**
     * Creates new form cancelorder
     */
    
    public cancelorder() {
        initComponents();
        try{
        Class.forName("oracle.jdbc.OracleDriver");
        //JOptionPane.showMessageDialog(this,"Driver Loaded!");
        try {
            con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:ORCL",
                    "scott","tiger");
            //JOptionPane.showMessageDialog(this,"Connected to Oracle database!");
        }
        catch (SQLException ex) {
            Logger.getLogger(cancelorder.class.getName()).log(Level.SEVERE,null, ex);
            JOptionPane.showMessageDialog(this,ex.getMessage());
        }
        }
        catch(ClassNotFoundException ex){
            Logger.getLogger(cancelorder.class.getName()).log(Level.SEVERE,null, ex);
            JOptionPane.showMessageDialog(this,ex.getMessage());
        }

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        icon = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        oid = new javax.swing.JTextField();
        confirmcancel = new javax.swing.JButton();
        home = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cancel Order");

        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inventory/cancel-order.png"))); // NOI18N

        title.setFont(new java.awt.Font("Gill Sans MT", 0, 48)); // NOI18N
        title.setText("Cancel Order");

        jLabel1.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        jLabel1.setText("Enter your order ID ");

        oid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oidActionPerformed(evt);
            }
        });

        confirmcancel.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        confirmcancel.setText("Confirm cancellation");
        confirmcancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                confirmcancelMouseClicked(evt);
            }
        });
        confirmcancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmcancelActionPerformed(evt);
            }
        });

        home.setText("Home");
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMouseClicked(evt);
            }
        });

        back.setText("Back");
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inventory/logo.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(home)
                .addGap(27, 27, 27)
                .addComponent(back)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(icon)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(oid, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(confirmcancel)))
                .addContainerGap(77, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(274, 274, 274)
                .addComponent(title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(title))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(home)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(icon, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(139, 139, 139)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(oid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(50, 50, 50)
                            .addComponent(confirmcancel)))
                    .addComponent(back))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void oidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oidActionPerformed

    private void confirmcancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmcancelMouseClicked
    String orderId = oid.getText(); // Get the order ID from the text field
    try{
   String orderDateSql = "SELECT OrderDate FROM Orders WHERE OrderID = ?";
ps = con.prepareStatement(orderDateSql);
ps.setString(1, orderId);
ResultSet orderDateResult = ps.executeQuery();


if (orderDateResult.next()) {

    // Get the orderDate from the result set
    Date orderDate = orderDateResult.getDate("OrderDate");

    java.sql.Date currentDate = new java.sql.Date(System.currentTimeMillis());

    long difference = ChronoUnit.DAYS.between(orderDate.toLocalDate(), currentDate.toLocalDate());

    if (difference < 7) {
       
        String deleteItemsSql = "DELETE FROM ordered_item WHERE orderid = ?";
        ps = con.prepareStatement(deleteItemsSql);
        ps.setString(1, orderId);
        int itemsDeleted = ps.executeUpdate();

        String deleteOrderSql = "DELETE FROM orders WHERE orderid = ?";
        ps = con.prepareStatement(deleteOrderSql);
        ps.setString(1, orderId);
        int orderDeleted = ps.executeUpdate();

        if (itemsDeleted > 0 && orderDeleted > 0) {
            JOptionPane.showMessageDialog(this, "Order canceled successfully!");
            
        } else {
            JOptionPane.showMessageDialog(this, "Order not found!");
            con.rollback();
        }

    } else {
        JOptionPane.showMessageDialog(this, "Cannot cancel the order. Delivery duration has passed.");
    }
} else {
    JOptionPane.showMessageDialog(this, "Order not found!");
}
}
    catch (SQLException ex){
        JOptionPane.showMessageDialog(this, "Error : "+ex.getMessage());
    }//GEN-LAST:event_confirmcancelMouseClicked
    }
    private void confirmcancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmcancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmcancelActionPerformed

    private void homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseClicked
 this.dispose();
        new home().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_homeMouseClicked

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
 this.dispose();
        new customer_entry().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_backMouseClicked

       


    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        /*try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cancelorder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cancelorder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cancelorder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cancelorder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }*/
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cancelorder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton confirmcancel;
    private javax.swing.JButton home;
    private javax.swing.JLabel icon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField oid;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
